### ISSUE TITLE
Gemfile.lock deleted - breaks deployment

### ISSUE THREAD

**Issue by cboltz** [openSUSE/security-team-blog#2]
You deleted Gemfile.lock with https://github.com/openSUSE/security-team-blog/commit/1ce2d9c0132e9924a2e686cbeeb6bcfa444df675 (while the commit message says "Updating Gemfile.lock")

Unfortunately that breaks the deployment on security.opensuse.org - the deployment script complains

```
The deployment setting requires a Gemfile.lock. Please make sure you have
checked your Gemfile.lock into version control before deploying.
```

Please re-add the Gemfile.lock.

**Comment by tacerus** [comment]
https://progress.opensuse.org/issues/163211

**Comment by mgerstner** [comment]
The problematic commit has been reverted, is deployment working again now?

**Comment by cboltz** [comment]
Unfortunately not, but we got some progress - a new error message ;-)

```
Bundler 2.3.27 is running, but your lockfile was generated with 2.4.10. Installing Bundler 2.4.10 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.4.10
Installing bundler 2.4.10
Fetching gem metadata from https://rubygems.org/...........
sass-embedded-1.77.2-x86_64-linux-gnu requires ruby version >= 3.2.0, which is
incompatible with the current version, 3.1.6
Exitstatus: 6
```

**Comment by mgerstner** [comment]
Thanks for providing the error message. This is not really my area of expertise... it seems Paolo (maybe unintentionally) updated the Gemfile.lock with new versions. I now reverted that update. Please keep us up-to-date if it helps.

**Comment by mgerstner** [comment]
It seems the deployment is working again now. Thanks for helping us out in the analysis. Closing as completed.
